name: Bug Report
description: Report a bug in ResearchGravity
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: "When I run X, I expected Y but got Z..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      value: |
        1. Run `python3 ...`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.11"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.0 / Ubuntu 22.04 / Windows 11"
